srcDir=src/main/java
webAppDir=src/main/webapp
buildDir=build
classDir=build/classes
warName=webLab4.war
version=1.0
mainClass=org.example.Main
testSrcDir = src/test/java
resourcesDir = src/main/resources
outputTest = build/test/reports
frontend = frontend
audioSrc= src/test/resources/notification.wav

org.gradle.daemon=false
org.gradle.vfs.watch=false
org.gradle.configureondemand=false
